<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>RFQ - {{ $rfq->rfq_no }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 14px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #2563eb;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #2563eb;
        }
        .info-section {
            width: 100%;
            margin-bottom: 30px;
        }
        .info-section td {
            padding: 5px;
            vertical-align: top;
        }
        .items-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }
        .items-table th, .items-table td {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
        }
        .items-table th {
            background-color: #f8f9fc;
            color: #1f2937;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 12px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>
</head>
<body>

    <div class="header">
        <h1>REQUEST FOR QUOTATION</h1>
        <h3>{{ $rfq->rfq_no }}</h3>
    </div>

    <table class="info-section">
        <tr>
            <td width="50%">
                <strong>To (Invited Vendor / Suppliers):</strong><br>
                @if(isset($vendor) && $vendor)
                    <strong>{{ $vendor->shop_name }}</strong><br>
                    {{ $vendor->email }}<br>
                    {{ $vendor->address }}
                @elseif(isset($rfq->vendors) && $rfq->vendors->count() > 0)
                    @foreach($rfq->vendors as $rv)
                        • <strong>{{ $rv->vendor->shop_name ?? 'Vendor' }}</strong> ({{ $rv->vendor->email ?? '' }})<br>
                    @endforeach
                @else
                    <em>All Invited Vendors / Suppliers</em>
                @endif
            </td>
            <td width="50%" style="text-align: right;">
                <strong>Date Issued:</strong> {{ $rfq->created_at->format('d M, Y') }}<br>
                <strong>Due Date:</strong> {{ $rfq->due_date ? $rfq->due_date->format('d M, Y') : 'N/A' }}<br>
                <strong>Status:</strong> <span style="text-transform: uppercase;">{{ $rfq->status }}</span>
            </td>
        </tr>
    </table>

    <table class="items-table">
        <thead>
            <tr>
                <th width="5%">#</th>
                <th width="65%">Product Description</th>
                <th width="30%" style="text-align: right;">Requested Qty</th>
            </tr>
        </thead>
        <tbody>
            @foreach($rfq->items as $index => $item)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>
                        <strong>{{ $item->product->name }}</strong>
                        @if($item->variant)
                            <br><small>{{ $item->variant->name }}</small>
                        @endif
                    </td>
                    <td style="text-align: right;">{{ $item->qty }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This is an automated RFQ document generated by B2BViking ERP.</p>
        <p>Please submit your quotation via the secure link provided in your email.</p>
    </div>

</body>
</html>
